openapi: 3.1.0
info:
  title: SpecBot Backend API
  version: 2.0.0
  description: |
    Backend API for SpecBot chat interface with OpenAI ChatGPT integration via LangChain.

    ## Overview
    This API routes user messages to OpenAI's ChatGPT model and returns AI-generated responses.
    Conversation history is included for context-aware conversations.

    ## Feature
    - **Feature ID**: 006-openai-langchain-chat
    - **Spec**: `specs/006-openai-langchain-chat/spec.md`
    - **Status**: Implementation

    ## Changes from v1.0.0
    - Response `message` field now contains AI response (no "api says: " prefix)
    - Added optional `history` field to request for conversation context
    - Added 504 Gateway Timeout for LLM timeouts
    - Updated 503 errors for AI service issues

  contact:
    name: SpecBot Development Team
  license:
    name: MIT

servers:
  - url: http://localhost:8000
    description: Local development server
  - url: http://127.0.0.1:8000
    description: Alternative localhost

tags:
  - name: messages
    description: Message sending and AI response operations
  - name: monitoring
    description: Health and status endpoints

paths:
  /api/v1/messages:
    post:
      tags:
        - messages
      summary: Send message and receive AI response
      description: |
        Accepts a user message with optional conversation history and returns an AI-generated response
        from OpenAI's ChatGPT via LangChain.

        **Implements**: spec.md User Stories 1-3

        **Acceptance Criteria**:
        - Response contains AI-generated reply (FR-001, FR-002)
        - Conversation history included for context (FR-003)
        - Loading state indicated during processing (FR-004)
        - Errors handled gracefully with user-friendly messages (FR-005, FR-006)
        - Response time under 10 seconds under normal conditions (SC-001)

      operationId: sendMessage
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessageRequest'
            examples:
              simpleMessage:
                summary: Simple message without history
                value:
                  message: "Hello, how are you?"
              messageWithHistory:
                summary: Message with conversation context
                value:
                  message: "What is my name?"
                  conversationId: "conv-a1b2c3d4-5678-90ab-cdef-123456789abc"
                  timestamp: "2026-01-10T12:00:00.000Z"
                  history:
                    - sender: "user"
                      text: "My name is Alice"
                    - sender: "system"
                      text: "Nice to meet you, Alice! How can I help you today?"
              specialCharacters:
                summary: Message with emoji and special characters
                value:
                  message: "What does 🚀 mean?"

      responses:
        '200':
          description: Success - AI response generated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
              examples:
                simpleResponse:
                  summary: AI response to greeting
                  value:
                    status: "success"
                    message: "Hello! I'm doing well, thank you for asking. How can I assist you today?"
                    timestamp: "2026-01-10T12:00:01.234Z"
                contextualResponse:
                  summary: AI response using conversation context
                  value:
                    status: "success"
                    message: "Your name is Alice, as you mentioned earlier."
                    timestamp: "2026-01-10T12:00:01.234Z"

        '400':
          description: Bad Request - Invalid message or content issue
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                emptyMessage:
                  summary: Empty message error
                  value:
                    status: "error"
                    error: "Message cannot be empty"
                    timestamp: "2026-01-10T12:00:01.234Z"
                contentFiltered:
                  summary: Content filtered by AI
                  value:
                    status: "error"
                    error: "Message could not be processed. Please try rephrasing."
                    timestamp: "2026-01-10T12:00:01.234Z"

        '422':
          description: Unprocessable Entity - Schema validation failure
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                missingField:
                  summary: Missing required field
                  value:
                    status: "error"
                    error: "Invalid request format"
                    detail:
                      field: "message"
                      issue: "Field required"
                    timestamp: "2026-01-10T12:00:01.234Z"

        '500':
          description: Internal Server Error - Unexpected server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                serverError:
                  summary: Internal server error
                  value:
                    status: "error"
                    error: "Internal server error occurred"
                    timestamp: "2026-01-10T12:00:01.234Z"

        '503':
          description: Service Unavailable - AI service issues
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                configError:
                  summary: AI configuration error (invalid API key)
                  value:
                    status: "error"
                    error: "AI service configuration error. Please contact support."
                    timestamp: "2026-01-10T12:00:01.234Z"
                rateLimited:
                  summary: AI service rate limited
                  value:
                    status: "error"
                    error: "AI service is busy. Please try again in a moment."
                    timestamp: "2026-01-10T12:00:01.234Z"
                connectionError:
                  summary: Cannot reach AI service
                  value:
                    status: "error"
                    error: "Unable to reach AI service. Please check your connection."
                    timestamp: "2026-01-10T12:00:01.234Z"

        '504':
          description: Gateway Timeout - AI request timed out
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                timeout:
                  summary: AI request timeout
                  value:
                    status: "error"
                    error: "Request timed out. Please try again."
                    timestamp: "2026-01-10T12:00:01.234Z"

  /health:
    get:
      tags:
        - monitoring
      summary: Health check endpoint
      description: Returns server health status for monitoring and load balancers
      operationId: healthCheck
      responses:
        '200':
          description: Server is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [ok]
                    example: "ok"
                required:
                  - status

components:
  schemas:
    MessageRequest:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          minLength: 1
          maxLength: 10000
          description: |
            User message text to be processed by the AI.

            **Validation**:
            - Cannot be empty or only whitespace
            - Maximum 10,000 characters
            - Preserves special characters, emoji, multi-byte characters
            - Supports line breaks and formatting

          examples:
            - "Hello, how are you?"
            - "What is the capital of France?"
            - "Explain quantum computing in simple terms"

        conversationId:
          type: string
          description: |
            Optional conversation ID for tracking.
            Format: conv-{uuid} where {uuid} is a standard UUID v4.

          pattern: '^conv-[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$'
          examples:
            - "conv-a1b2c3d4-5678-90ab-cdef-123456789abc"

        timestamp:
          type: string
          format: date-time
          description: Client-side timestamp of message creation (ISO-8601 format)
          examples:
            - "2026-01-10T12:00:00.000Z"

        history:
          type: array
          description: |
            Optional conversation history for context.
            Include previous messages to enable multi-turn conversations.
            The current message should NOT be included in history.

          items:
            type: object
            required:
              - sender
              - text
            properties:
              sender:
                type: string
                enum: [user, system]
                description: Message sender type
              text:
                type: string
                minLength: 1
                description: Message content
          examples:
            - - sender: "user"
                text: "My name is Alice"
              - sender: "system"
                text: "Nice to meet you, Alice!"

    MessageResponse:
      type: object
      required:
        - status
        - message
        - timestamp
      properties:
        status:
          type: string
          enum: [success]
          description: Response status indicator
          example: "success"

        message:
          type: string
          description: |
            AI-generated response to the user's message.

            **Characteristics**:
            - Generated by OpenAI ChatGPT via LangChain
            - Context-aware when conversation history provided
            - May include formatting, lists, code blocks

          examples:
            - "Hello! I'm doing well, thank you for asking."
            - "The capital of France is Paris."
            - "Your name is Alice, as you mentioned earlier."

        timestamp:
          type: string
          format: date-time
          description: Server-side timestamp of response creation (ISO-8601)
          examples:
            - "2026-01-10T12:00:01.234Z"

    ErrorResponse:
      type: object
      required:
        - status
        - error
        - timestamp
      properties:
        status:
          type: string
          enum: [error]
          description: Response status indicator
          example: "error"

        error:
          type: string
          description: |
            Human-readable error message.

            **Security**: Never exposes internal details, API keys, or raw error messages.

          examples:
            - "Message cannot be empty"
            - "AI service is busy. Please try again in a moment."
            - "Request timed out. Please try again."

        detail:
          type: object
          description: Optional additional error context for validation errors
          additionalProperties: true
          examples:
            - field: "message"
              issue: "Field required"

        timestamp:
          type: string
          format: date-time
          description: Server-side timestamp of error occurrence
          examples:
            - "2026-01-10T12:00:01.234Z"

  securitySchemes: {}

security: []

x-requirements-mapping:
  FR-001: "System sends user messages to OpenAI ChatGPT (POST /api/v1/messages)"
  FR-002: "System displays AI responses (MessageResponse.message)"
  FR-003: "System includes conversation history (MessageRequest.history)"
  FR-004: "System displays loading indicator (client responsibility)"
  FR-005: "System handles API errors (503/504 responses)"
  FR-006: "System does NOT expose sensitive information (ErrorResponse sanitized)"
  FR-007: "System uses LangChain (implementation detail)"
  FR-008: "System supports API key configuration (server-side env var)"
  FR-009: "System distinguishes user/AI messages (client responsibility)"
  FR-010: "System preserves message order (client responsibility)"
